# Generated by Django 6.0.1 on 2026-01-16 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type_personnel', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, help_text='Digital signature in base64 format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base Staff',
                'verbose_name_plural': 'Base Staffs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Administrative',
            fields=[
                ('base_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='administrative_profile', serialize=False, to='staff.basestaff')),
                ('department', models.CharField(help_text='Department where the administrative staff works', max_length=100)),
                ('role', models.CharField(help_text='Role of the administrative staff', max_length=100)),
                ('access_level', models.CharField(help_text='Access level of the administrative staff', max_length=50)),
            ],
            options={
                'verbose_name': 'Administrative Staff',
                'verbose_name_plural': 'Administrative Staffs',
                'ordering': ['-base_staff__created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('base_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver_profile', serialize=False, to='staff.basestaff')),
                ('license_number', models.CharField(help_text='Driver license number', max_length=50, unique=True)),
                ('license_category', models.CharField(help_text='Category of the driver license', max_length=20)),
                ('license_expiry_date', models.DateField(help_text='Expiry date of the driver license')),
                ('license_issue_date', models.DateField(help_text='Issue date of the driver license')),
                ('blood_type', models.CharField(help_text='Blood type of the driver', max_length=5)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['-base_staff__created_at'],
            },
        ),
        migrations.CreateModel(
            name='Healthcare',
            fields=[
                ('base_staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='healthcare_profile', serialize=False, to='staff.basestaff')),
                ('professional_registration', models.CharField(help_text='Professional registration number', max_length=50, unique=True)),
                ('professional_position', models.CharField(help_text='Position held by the healthcare staff', max_length=50)),
            ],
            options={
                'verbose_name': 'Healthcare Staff',
                'verbose_name_plural': 'Healthcare Staffs',
                'ordering': ['-base_staff__created_at'],
            },
        ),
    ]
