# Generated by Django 6.0.1 on 2026-01-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basestaff',
            name='signature',
        ),
        migrations.AlterField(
            model_name='basestaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='basestaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated'),
        ),
    ]
