# Generated by Django 6.0.1 on 2026-01-21 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_monthly_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="additionals",
            name="tablet",
            field=models.IntegerField(
                default=0,
                help_text="Tablet quantity",
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
