# Generated by Django 6.0.1 on 2026-01-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_monthly_inventory", "0002_additionals_tablet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shift name: day or night", max_length=50, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="dailymonthlyinventory",
            name="support_staff",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="dailymonthlyinventory",
            name="ambulance",
            field=models.ForeignKey(
                blank=True,
                max_length=128,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="daily_monthly_inventory.ambulance",
            ),
        ),
        migrations.AddField(
            model_name="dailymonthlyinventory",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="daily_monthly_inventory.shift",
            ),
        ),
    ]
