# Generated by Django 6.0.1 on 2026-01-23 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_monthly_inventory", "0004_dailymonthlyinventory_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessories",
            name="adult_pediatric_stethoscope",
            field=models.IntegerField(
                blank=True,
                help_text="Adult/pediatric stethoscope quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="adult_sphygmomanometer",
            field=models.IntegerField(
                blank=True,
                help_text="Adult sphygmomanometer quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="chemical_attack_kit_forms",
            field=models.IntegerField(
                blank=True,
                help_text="Chemical attack kit forms quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="chemical_attack_kit_ph_tape",
            field=models.IntegerField(
                blank=True,
                help_text="Chemical attack kit pH tape quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="clean_gauze_pack",
            field=models.IntegerField(
                blank=True,
                help_text="Clean gauze pack quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="eucida_advanced_disinfectant",
            field=models.IntegerField(
                blank=True,
                help_text="Eucida advanced disinfectant quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="female_urinal",
            field=models.IntegerField(
                blank=True,
                help_text="Female urinal quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="gloves_boxes",
            field=models.IntegerField(
                blank=True,
                help_text="Gloves boxes quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="male_urinal",
            field=models.IntegerField(
                blank=True,
                help_text="Male urinal quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="patient_blanket",
            field=models.IntegerField(
                blank=True,
                help_text="Patient blanket quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="red_biohazard_bags",
            field=models.IntegerField(
                blank=True,
                help_text="Red biohazard bags quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="red_biohazard_container",
            field=models.IntegerField(
                blank=True,
                help_text="Red biohazard container quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="short_spinal_board",
            field=models.IntegerField(
                blank=True,
                help_text="Short spinal board quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="stretcher_sheet",
            field=models.IntegerField(
                blank=True,
                help_text="Stretcher sheet quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="thermo_hygrometer",
            field=models.IntegerField(
                blank=True,
                help_text="Thermo hygrometer quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="wheelchair",
            field=models.IntegerField(
                blank=True,
                help_text="Wheelchair quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="white_waste_bags",
            field=models.IntegerField(
                blank=True,
                help_text="White waste bags quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="white_waste_container",
            field=models.IntegerField(
                blank=True,
                help_text="White waste container quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessories",
            name="wypall_towels",
            field=models.IntegerField(
                blank=True,
                help_text="Wypall towels quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="accessoriescase",
            name="adult_bp_cuff",
            field=models.IntegerField(
                blank=True,
                help_text="Adult BP cuff quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessoriescase",
            name="adult_spo2_sensor",
            field=models.IntegerField(
                blank=True,
                help_text="Adult SPO2 sensor quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessoriescase",
            name="carsioscope_cables",
            field=models.IntegerField(
                blank=True,
                help_text="Cardiac SPO2 sensor quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessoriescase",
            name="pediatric_bp_cuff",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric BP cuff quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessoriescase",
            name="pediatric_spo2_sensor",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric SPO2 sensor quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="accessoriescase",
            name="temperature_sensor",
            field=models.IntegerField(
                blank=True,
                help_text="Temperature sensor quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="additionals",
            name="artificial_tears",
            field=models.IntegerField(
                blank=True,
                help_text="Artificial tears quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="additionals",
            name="charger",
            field=models.IntegerField(
                blank=True,
                help_text="Charger quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="additionals",
            name="cleaning_log_form",
            field=models.IntegerField(
                blank=True,
                help_text="Cleaning log form quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="additionals",
            name="data_clipboard_board",
            field=models.IntegerField(
                blank=True,
                help_text="Data clipboard board quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="additionals",
            name="medical_record_forms",
            field=models.IntegerField(
                blank=True,
                help_text="Medical record forms quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="additionals",
            name="tablet",
            field=models.IntegerField(
                blank=True,
                help_text="Tablet quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="additionals",
            name="temperature_log_form",
            field=models.IntegerField(
                blank=True,
                help_text="Temperature log form quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="adhesive_tape",
            field=models.IntegerField(
                blank=True,
                help_text="Adhesive tape quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="alcohol_pads",
            field=models.IntegerField(
                blank=True,
                help_text="Alcohol pads quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="clinical_thermometer",
            field=models.IntegerField(
                blank=True,
                help_text="Clinical thermometer quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="cotton_tipped_applicators",
            field=models.IntegerField(
                blank=True,
                help_text="Cotton-tipped applicators quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="eye_patches",
            field=models.IntegerField(
                blank=True,
                help_text="Eye patches quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="hemorrhage_control_tourniquet",
            field=models.IntegerField(
                blank=True,
                help_text="Hemorrhage control tourniquet quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="iv_tourniquet",
            field=models.IntegerField(
                blank=True,
                help_text="IV tourniquet quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="medical_penlight",
            field=models.IntegerField(
                blank=True,
                help_text="Medical penlight quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="micropore_tape",
            field=models.IntegerField(
                blank=True,
                help_text="Micropore tape quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="n95_masks",
            field=models.IntegerField(
                blank=True,
                help_text="N95 masks quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="sanitary_pads",
            field=models.IntegerField(
                blank=True,
                help_text="Sanitary pads quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="sterile_gauze_kit",
            field=models.IntegerField(
                blank=True,
                help_text="Sterile gauze kit quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="surgical_masks",
            field=models.IntegerField(
                blank=True,
                help_text="Surgical masks quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="tongue_depressors",
            field=models.IntegerField(
                blank=True,
                help_text="Tongue depressors quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="ambulancekit",
            name="trauma_shears",
            field=models.IntegerField(
                blank=True,
                help_text="Trauma shears quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="adult_pads",
            field=models.IntegerField(
                blank=True,
                help_text="Adult pads quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="aed",
            field=models.IntegerField(
                blank=True,
                help_text="AED quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="aspirator",
            field=models.IntegerField(
                blank=True,
                help_text="Aspirator quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="central_oxygen",
            field=models.IntegerField(
                blank=True,
                help_text="Central oxygen quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="flowmeter",
            field=models.IntegerField(
                blank=True,
                help_text="Flowmeter quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="glucometer",
            field=models.IntegerField(
                blank=True,
                help_text="Glucometer quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="monitor",
            field=models.IntegerField(
                blank=True,
                help_text="Monitor quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="pediatric_pads",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric pads quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="portable_oxygen_1",
            field=models.IntegerField(
                blank=True,
                help_text="Portable oxygen #1 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="portable_oxygen_2",
            field=models.IntegerField(
                blank=True,
                help_text="Portable oxygen #2 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="pulse_oximeter",
            field=models.IntegerField(
                blank=True,
                help_text="Pulse oximeter quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="reflex_hammer",
            field=models.IntegerField(
                blank=True,
                help_text="Reflex hammer quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="search_light",
            field=models.IntegerField(
                blank=True,
                help_text="Search light quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="biomedicalequipment",
            name="spencer_scissors",
            field=models.IntegerField(
                blank=True,
                help_text="Spencer scissors quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="dextrose_10_percent",
            field=models.IntegerField(
                blank=True,
                help_text="Dextrose 10% quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="dextrose_5_percent",
            field=models.IntegerField(
                blank=True,
                help_text="Dextrose 5% quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="hartmann_lactate_solution",
            field=models.IntegerField(
                blank=True,
                help_text="Hartmann lactate solution quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="iv_catheter_14g",
            field=models.IntegerField(
                blank=True,
                help_text="IV catheter 14G quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="iv_catheter_16g",
            field=models.IntegerField(
                blank=True,
                help_text="IV catheter 16G quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="iv_catheter_18g",
            field=models.IntegerField(
                blank=True,
                help_text="IV catheter 18G quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="iv_catheter_20g",
            field=models.IntegerField(
                blank=True,
                help_text="IV catheter 20G quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="iv_catheter_22g",
            field=models.IntegerField(
                blank=True,
                help_text="IV catheter 22G quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="iv_catheter_24g",
            field=models.IntegerField(
                blank=True,
                help_text="IV catheter 24G quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="macro_drip_set",
            field=models.IntegerField(
                blank=True,
                help_text="Macro drip set quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="micro_drip_set",
            field=models.IntegerField(
                blank=True,
                help_text="Micro drip set quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="saline_solution_09_500cc",
            field=models.IntegerField(
                blank=True,
                help_text="Saline solution 0.9% 500cc quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="scalp_vein_set_21g",
            field=models.IntegerField(
                blank=True,
                help_text="Scalp vein set 21G quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="scalp_vein_set_22g",
            field=models.IntegerField(
                blank=True,
                help_text="Scalp vein set 22G quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="scalp_vein_set_23g",
            field=models.IntegerField(
                blank=True,
                help_text="Scalp vein set 23G quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="sharps_container",
            field=models.IntegerField(
                blank=True,
                help_text="Sharps container quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="sterile_water",
            field=models.IntegerField(
                blank=True,
                help_text="Sterile water quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="syringe_10cc",
            field=models.IntegerField(
                blank=True,
                help_text="Syringe 10cc quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="syringe_1cc",
            field=models.IntegerField(
                blank=True,
                help_text="Syringe 1cc quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="syringe_20cc",
            field=models.IntegerField(
                blank=True,
                help_text="Syringe 20cc quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="syringe_3cc",
            field=models.IntegerField(
                blank=True,
                help_text="Syringe 3cc quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="syringe_50cc",
            field=models.IntegerField(
                blank=True,
                help_text="Syringe 50cc quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="circulatory",
            name="syringe_5cc",
            field=models.IntegerField(
                blank=True,
                help_text="Syringe 5cc quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="immobilizationandsafety",
            name="adult_cervical_collar",
            field=models.IntegerField(
                blank=True,
                help_text="Adult cervical collar quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="immobilizationandsafety",
            name="adult_immobilization_kit",
            field=models.IntegerField(
                blank=True,
                help_text="Adult immobilization kit quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="immobilizationandsafety",
            name="ambumedic_umbrella",
            field=models.IntegerField(
                blank=True,
                help_text="Ambumedic umbrella quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="immobilizationandsafety",
            name="benziral_spill_kit",
            field=models.IntegerField(
                blank=True,
                help_text="Benziral spill kit quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="immobilizationandsafety",
            name="pediatric_cervical_collar",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric cervical collar quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="immobilizationandsafety",
            name="pediatric_immobilization_kit",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric immobilization kit quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="immobilizationandsafety",
            name="safety_vests",
            field=models.IntegerField(
                blank=True,
                help_text="Safety vests quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="immobilizationandsafety",
            name="stretcher_harness_straps",
            field=models.IntegerField(
                blank=True,
                help_text="Stretcher harness straps quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="immobilizationandsafety",
            name="stretcher_side_rails",
            field=models.IntegerField(
                blank=True,
                help_text="Stretcher side rails quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="immobilizationandsafety",
            name="west_solidifier_spill_kit",
            field=models.IntegerField(
                blank=True,
                help_text="West solidifier spill kit quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="laryngeal_mask_1_5",
            field=models.IntegerField(
                blank=True,
                help_text="Laryngeal mask 1.5 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="laryngeal_mask_2",
            field=models.IntegerField(
                blank=True,
                help_text="Laryngeal mask #2 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="laryngeal_mask_3",
            field=models.IntegerField(
                blank=True,
                help_text="Laryngeal mask #3 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="oropharyngeal_airway_0",
            field=models.IntegerField(
                blank=True,
                help_text="Oropharyngeal airway #0 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="oropharyngeal_airway_1",
            field=models.IntegerField(
                blank=True,
                help_text="Oropharyngeal airway #1 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="oropharyngeal_airway_2",
            field=models.IntegerField(
                blank=True,
                help_text="Oropharyngeal airway #2 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="pediatric_bvm_bag_valve_mask",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric BVM bag valve mask quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="pediatric_nasal_cannula",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric nasal cannula quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="pediatric_nebulizer_kit",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric nebulizer kit quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="pediatric_non_rebreather_mask",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric non-rebreather mask quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="pediatric_simple_mask",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric simple mask quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="pediatric_sphygmomanometer",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric sphygmomanometer quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="pediatric_venturi_system",
            field=models.IntegerField(
                blank=True,
                help_text="Pediatric venturi system quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="suction_bulb_aspirator",
            field=models.IntegerField(
                blank=True,
                help_text="Suction bulb aspirator quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="pediatric",
            name="umbilical_cord_clamp",
            field=models.IntegerField(
                blank=True,
                help_text="Umbilical cord clamp quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="adult_bvm_bag_valve_mask",
            field=models.IntegerField(
                blank=True,
                help_text="Adult BVM bag valve mask quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="adult_nasal_cannula",
            field=models.IntegerField(
                blank=True,
                help_text="Adult nasal cannula quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="adult_nebulizer_kit",
            field=models.IntegerField(
                blank=True,
                help_text="Adult nebulizer kit quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="adult_non_rebreather_mask",
            field=models.IntegerField(
                blank=True,
                help_text="Adult non-rebreather mask quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="adult_simple_mask",
            field=models.IntegerField(
                blank=True,
                help_text="Adult simple mask quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="adult_spacer_chamber",
            field=models.IntegerField(
                blank=True,
                help_text="Adult spacer chamber quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="adult_venturi_system",
            field=models.IntegerField(
                blank=True,
                help_text="Adult venturi system quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="laryngeal_mask_4",
            field=models.IntegerField(
                blank=True,
                help_text="Laryngeal mask #4 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="laryngeal_mask_5",
            field=models.IntegerField(
                blank=True,
                help_text="Laryngeal mask #5 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="o2_connecting_tube",
            field=models.IntegerField(
                blank=True,
                help_text="O2 connecting tube quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="oropharyngeal_airway_3",
            field=models.IntegerField(
                blank=True,
                help_text="Oropharyngeal airway #3 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="oropharyngeal_airway_4",
            field=models.IntegerField(
                blank=True,
                help_text="Oropharyngeal airway #4 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="oropharyngeal_airway_5",
            field=models.IntegerField(
                blank=True,
                help_text="Oropharyngeal airway #5 quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="simple_humidifier_jar",
            field=models.IntegerField(
                blank=True,
                help_text="Simple humidifier jar quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="suction_catheter",
            field=models.IntegerField(
                blank=True,
                help_text="Suction catheter quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="suction_tubing",
            field=models.IntegerField(
                blank=True,
                help_text="Suction tubing quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="venturi_humidifier_jar",
            field=models.IntegerField(
                blank=True,
                help_text="Venturi humidifier jar quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="respiratory",
            name="yankauer_suction_tip",
            field=models.IntegerField(
                blank=True,
                help_text="Yankauer suction tip quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="alcohol_120ml",
            field=models.IntegerField(
                blank=True,
                help_text="Alcohol 120ml quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="antiseptic_soap",
            field=models.IntegerField(
                blank=True,
                help_text="Antiseptic soap quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="cotton_bundle",
            field=models.IntegerField(
                blank=True,
                help_text="Cotton bundle quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="elastic_bandage",
            field=models.IntegerField(
                blank=True,
                help_text="Elastic bandage quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="gauze_bandage",
            field=models.IntegerField(
                blank=True,
                help_text="Gauze bandage quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="gauze_compress",
            field=models.IntegerField(
                blank=True,
                help_text="Gauze compress quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="kidney_dish",
            field=models.IntegerField(
                blank=True,
                help_text="Kidney dish quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="magill_forceps",
            field=models.IntegerField(
                blank=True,
                help_text="Magill forceps quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="safety_goggles",
            field=models.IntegerField(
                blank=True,
                help_text="Safety goggles quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="sterile_gloves",
            field=models.IntegerField(
                blank=True,
                help_text="Sterile gloves quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="sterile_surgical_gauze",
            field=models.IntegerField(
                blank=True,
                help_text="Sterile surgical gauze quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="surgical_soap",
            field=models.IntegerField(
                blank=True,
                help_text="Surgical soap quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="thermal_blanket",
            field=models.IntegerField(
                blank=True,
                help_text="Thermal blanket quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="surgical",
            name="triangular_bandage",
            field=models.IntegerField(
                blank=True,
                help_text="Triangular bandage quantity",
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
    ]
