# Generated by Django 6.0.1 on 2026-01-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "daily_monthly_inventory",
            "0005_alter_accessories_adult_pediatric_stethoscope_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymonthlyinventory",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
