# Generated by Django 6.0.1 on 2026-01-28 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_monthly_inventory", "0006_dailymonthlyinventory_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionals",
            name="observations_comments",
            field=models.TextField(
                blank=True, help_text="Observations and comments", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="license_plate",
            field=models.TextField(blank=True, help_text="Observations and comments"),
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="mobile_number",
            field=models.IntegerField(
                help_text="Mobile number",
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AlterField(
            model_name="dailymonthlyinventory",
            name="support_staff",
            field=models.TextField(blank=True, null=True),
        ),
    ]
