# Generated by Django 6.0.1 on 2026-01-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='cie_10_name',
            field=models.CharField(max_length=500),
        ),
    ]
