# Generated by Django 6.0.1 on 2026-01-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0002_alter_diagnosis_cie_10_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the receiving institution', max_length=200, unique=True, verbose_name='Name of Institution')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Occupational Risk Management',
                'verbose_name_plural': 'Occupational Risk Managements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the health promoting entity', max_length=200, unique=True, verbose_name='Name of Institution')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Health Promoting Entity',
                'verbose_name_plural': 'Health Promoting Entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the receiving institution', max_length=200, unique=True, verbose_name='Name of Institution')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Receiving Institution',
                'verbose_name_plural': 'Receiving Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SOAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the institution', max_length=200, unique=True, verbose_name='Name of Institution')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Mandatory Traffic Accident Insurance',
                'verbose_name_plural': 'Mandatory Traffic Accident Insurances',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='cie_10_name',
            field=models.TextField(),
        ),
    ]
