# Generated by Django 6.0.1 on 2026-01-26 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0003_arl_eps_ips_soat_alter_diagnosis_cie_10_name'),
        ('staff', '0002_remove_basestaff_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretransferreport',
            name='companion_1',
        ),
        migrations.RemoveField(
            model_name='caretransferreport',
            name='companion_2',
        ),
        migrations.RemoveField(
            model_name='companion',
            name='is_responsible',
        ),
        migrations.RemoveField(
            model_name='companion',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='outgoingreceivingentity',
            name='signature',
        ),
        migrations.AddField(
            model_name='caretransferreport',
            name='companion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion_care_transfer_reports', to='patient_transport_report.companion'),
        ),
        migrations.AddField(
            model_name='caretransferreport',
            name='companion_is_responsible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caretransferreport',
            name='receiving_entity_signature',
            field=models.TextField(blank=True, help_text='Digital signature in base64 format', null=True),
        ),
        migrations.AddField(
            model_name='caretransferreport',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_care_transfer_reports', to='patient_transport_report.companion'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='attending_staff_signature',
            field=models.TextField(blank=True, help_text='Digital signature in base64 format', null=True),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='outgoing_entity_signature',
            field=models.TextField(blank=True, help_text='Digital signature in base64 format', null=True),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='patient_signature',
            field=models.TextField(blank=True, help_text='Digital signature in base64 format', null=True),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='responsible_signature',
            field=models.TextField(blank=True, help_text='Digital signature in base64 format', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='receiving_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_entity_care_transfer_report', to='patient_transport_report.outgoingreceivingentity'),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='attending_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_staff_informed_consents', to='staff.healthcare'),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='consent_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='outgoing_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_entity_informed_consents', to='patient_transport_report.outgoingreceivingentity'),
        ),
    ]
