# Generated by Django 6.0.1 on 2026-01-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_monthly_inventory', '0006_dailymonthlyinventory_is_deleted'),
        ('patient_transport_report', '0004_remove_caretransferreport_companion_1_and_more'),
        ('staff', '0002_remove_basestaff_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companion',
            name='email',
        ),
        migrations.RemoveField(
            model_name='result',
            name='receiving_institution',
        ),
        migrations.AddField(
            model_name='caretransferreport',
            name='ips',
            field=models.ForeignKey(blank=True, help_text='IPS associated with the care transfer report', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ips_care_transfer_reports', to='patient_transport_report.ips'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='ambulance',
            field=models.ForeignKey(blank=True, help_text='Ambulance used for the transport', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_care_transfer_reports', to='daily_monthly_inventory.ambulance'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='arrival_time_patient',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the ambulance arrived at the destination with the patient', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='attending_staff',
            field=models.ForeignKey(help_text='Healthcare staff attending the patient', on_delete=django.db.models.deletion.CASCADE, related_name='attending_staff_care_transfer_reports', to='staff.healthcare'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='attending_staff_tittle',
            field=models.CharField(blank=True, help_text='Title of the attending staff', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='companion',
            field=models.ForeignKey(blank=True, help_text='Companion accompanying the patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companion_care_transfer_reports', to='patient_transport_report.companion'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='companion_is_responsible',
            field=models.BooleanField(blank=True, help_text='Indicates if the companion is the responsible guardian', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='complications_transfer',
            field=models.OneToOneField(blank=True, help_text='Complications that occurred during the transfer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complications_transfer_care_transfer_report', to='patient_transport_report.complicationstransfer'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='diagnosis_1',
            field=models.ForeignKey(blank=True, help_text='Primary diagnosis of the patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_1_care_transfer_reports', to='patient_transport_report.diagnosis'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='diagnosis_2',
            field=models.ForeignKey(blank=True, help_text='Secondary diagnosis of the patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_2_care_transfer_reports', to='patient_transport_report.diagnosis'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='dispatch_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the ambulance was dispatched', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='double_arrival_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the ambulance arrived back at the base', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='double_departure_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the ambulance departed from the destination', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver of the ambulance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_care_transfer_reports', to='staff.driver'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='end_attention_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the care attention ended', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='final_physical_examination',
            field=models.OneToOneField(blank=True, help_text='Final physical examination of the patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_physical_exam_care_transfer_report', to='patient_transport_report.physicalexam'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='hemodynamic_statuses',
            field=models.ManyToManyField(blank=True, help_text='Select 1 or 2 hemodynamic statuses', related_name='care_transfer_reports', to='patient_transport_report.hemodynamicstatus'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='initial_address',
            field=models.CharField(blank=True, help_text='Initial address of the patient', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='initial_physicial_examination',
            field=models.OneToOneField(blank=True, help_text='Initial physical examination of the patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_physical_exam_care_transfer_report', to='patient_transport_report.physicalexam'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='landmark',
            field=models.CharField(blank=True, help_text='Landmark near the initial address', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes regarding the care transfer', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='patient_arrival_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the ambulance arrived at the patient location', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='patient_departure_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the ambulance departed from the patient location', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='patient_one_of',
            field=models.IntegerField(blank=True, help_text='Unique identifier for the patient within the care transfer report', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='receiving_entity',
            field=models.ForeignKey(blank=True, help_text='Entity receiving the patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_entity_care_transfer_report', to='patient_transport_report.outgoingreceivingentity'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='reg_number',
            field=models.CharField(blank=True, help_text='Registration number of the attending staff', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Responsible companion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_care_transfer_reports', to='patient_transport_report.companion'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='result',
            field=models.OneToOneField(blank=True, help_text='Results obtained during the transport', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_care_transfer_report', to='patient_transport_report.result'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='service_type',
            field=models.CharField(blank=True, help_text='Type of service provided', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='skin_conditions',
            field=models.ManyToManyField(blank=True, help_text='Select 1 or 2 skin conditions', related_name='care_transfer_reports', to='patient_transport_report.skincondition'),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='support_staff',
            field=models.CharField(blank=True, help_text='Support healthcare staff attending the patient', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='transfer_type',
            field=models.CharField(blank=True, help_text='Type of transfer (e.g., emergency, non-emergency)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='treatment',
            field=models.OneToOneField(blank=True, help_text='Treatment provided during the transport', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_care_transfer_report', to='patient_transport_report.treatment'),
        ),
        migrations.AlterField(
            model_name='companion',
            name='identification_number',
            field=models.CharField(blank=True, help_text='Identification document number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companion',
            name='identification_type',
            field=models.CharField(blank=True, help_text='Type of identification document', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companion',
            name='kindship',
            field=models.CharField(blank=True, help_text='Relationship to the patient', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companion',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the companion', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companion',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complicationstransfer',
            name='code',
            field=models.CharField(blank=True, help_text='Code associated with the complication', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complicationstransfer',
            name='description_complication',
            field=models.TextField(blank=True, help_text='Description of the complication that occurred during transfer', null=True),
        ),
        migrations.AlterField(
            model_name='complicationstransfer',
            name='record_waiting_time',
            field=models.BooleanField(blank=True, help_text='Indicates if waiting time was recorded', null=True),
        ),
        migrations.AlterField(
            model_name='complicationstransfer',
            name='register_code',
            field=models.BooleanField(blank=True, help_text='Indicates if a register code was recorded', null=True),
        ),
        migrations.AlterField(
            model_name='complicationstransfer',
            name='time_code',
            field=models.CharField(blank=True, help_text='Time associated with the code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complicationstransfer',
            name='waiting_time',
            field=models.DurationField(blank=True, help_text='Waiting time duration', null=True),
        ),
        migrations.AlterField(
            model_name='glasgow',
            name='eyes_opening',
            field=models.IntegerField(blank=True, help_text='Eye opening response score', null=True),
        ),
        migrations.AlterField(
            model_name='glasgow',
            name='eyes_opening_text',
            field=models.CharField(blank=True, help_text='Description of eye opening response', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='glasgow',
            name='motor',
            field=models.IntegerField(blank=True, help_text='Motor response score', null=True),
        ),
        migrations.AlterField(
            model_name='glasgow',
            name='motor_text',
            field=models.CharField(blank=True, help_text='Description of motor response', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='glasgow',
            name='total',
            field=models.IntegerField(blank=True, help_text='Total Glasgow Coma Scale score', null=True),
        ),
        migrations.AlterField(
            model_name='glasgow',
            name='verbal',
            field=models.IntegerField(blank=True, help_text='Verbal response score', null=True),
        ),
        migrations.AlterField(
            model_name='glasgow',
            name='verbal_text',
            field=models.CharField(blank=True, help_text='Description of verbal response', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='administers_medications',
            field=models.BooleanField(blank=True, help_text='Indicates if medication administration is consented', null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='attending_staff',
            field=models.ForeignKey(blank=True, help_text='Healthcare staff attending during consent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending_staff_informed_consents', to='staff.healthcare'),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consent was given', null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='guardian_id_number',
            field=models.CharField(blank=True, help_text='Identification number of the guardian', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='guardian_id_type',
            field=models.CharField(blank=True, help_text='Type of identification for the guardian (e.g., ID card, passport)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='guardian_name',
            field=models.CharField(blank=True, help_text='Name of the guardian or responsible person', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='guardian_type',
            field=models.CharField(blank=True, help_text='Type of guardian (e.g., parent, legal representative)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='medication_administration',
            field=models.OneToOneField(blank=True, help_text='Details about medication administration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_administration_informed_consent', to='patient_transport_report.medicationadministration'),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='other_implications',
            field=models.TextField(blank=True, help_text='Other implications explained to the patient/guardian', null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='outgoing_entity',
            field=models.ForeignKey(blank=True, help_text='Entity receiving the informed consent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_entity_informed_consents', to='patient_transport_report.outgoingreceivingentity'),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='patient_can_sign',
            field=models.BooleanField(blank=True, help_text='Indicates if the patient is able to sign the consent', null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='required_procedures',
            field=models.OneToOneField(blank=True, help_text='Procedures that require consent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_procedures_informed_consent', to='patient_transport_report.requiredprocedures'),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='responsible_can_sign',
            field=models.BooleanField(blank=True, help_text='Indicates if the responsible guardian can sign the consent', null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='responsible_for',
            field=models.CharField(blank=True, help_text='Name of the person the guardian is responsible for', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='service_type',
            field=models.CharField(blank=True, help_text='Type of service provided', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='admin_route_type',
            field=models.BooleanField(blank=True, help_text='Indicates the type of administration route used', null=True),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='iv_fluids',
            field=models.BooleanField(blank=True, help_text='Indicates if IV fluids were administered', null=True),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='other_medication_details',
            field=models.TextField(blank=True, help_text='Details of other medications administered', null=True),
        ),
        migrations.AlterField(
            model_name='medicationadministration',
            name='oxygen',
            field=models.BooleanField(blank=True, help_text='Indicates if oxygen was administered', null=True),
        ),
        migrations.AlterField(
            model_name='outgoingreceivingentity',
            name='document',
            field=models.CharField(blank=True, help_text='Document identifier of the entity', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingreceivingentity',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the outgoing or receiving entity', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingreceivingentity',
            name='staff_title',
            field=models.CharField(blank=True, help_text='Title or position of the staff member representing the entity', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patienttransportreport',
            name='care_transfer_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_care_transfer_report', to='patient_transport_report.caretransferreport'),
        ),
        migrations.AlterField(
            model_name='patienttransportreport',
            name='informed_consent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_informed_consent', to='patient_transport_report.informedconsent'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='blood_glucose',
            field=models.FloatField(blank=True, help_text='Blood glucose level', null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='diastolic',
            field=models.FloatField(blank=True, help_text='Diastolic blood pressure value', null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='glasgow',
            field=models.OneToOneField(blank=True, help_text='Glasgow Coma Scale assessment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physical_exam_glasgow', to='patient_transport_report.glasgow'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='heart_rate',
            field=models.FloatField(blank=True, help_text='Heart rate value', null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='map_pam',
            field=models.FloatField(blank=True, help_text='Mean arterial pressure (PAM) value', null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='oxygen_saturation',
            field=models.FloatField(blank=True, help_text='Oxygen saturation percentage', null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='respiratory_rate',
            field=models.FloatField(blank=True, help_text='Respiratory rate value', null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='systolic',
            field=models.FloatField(blank=True, help_text='Systolic blood pressure value', null=True),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Body temperature value', null=True),
        ),
        migrations.AlterField(
            model_name='requiredprocedures',
            name='ambulance_transport',
            field=models.BooleanField(blank=True, help_text='Indicates if ambulance transport was required', null=True),
        ),
        migrations.AlterField(
            model_name='requiredprocedures',
            name='assessment',
            field=models.BooleanField(blank=True, help_text='Indicates if patient assessment was required', null=True),
        ),
        migrations.AlterField(
            model_name='requiredprocedures',
            name='immovilization',
            field=models.BooleanField(blank=True, help_text='Indicates if immovilization was required', null=True),
        ),
        migrations.AlterField(
            model_name='requiredprocedures',
            name='other_procedures_details',
            field=models.TextField(blank=True, help_text='Details of other required procedures', null=True),
        ),
        migrations.AlterField(
            model_name='requiredprocedures',
            name='streatcher_transfer',
            field=models.BooleanField(blank=True, help_text='Indicates if stretcher transfer was required', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='denies_transportation',
            field=models.BooleanField(blank=True, help_text='Indicates if the patient denies transportation', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='no_vital_signs',
            field=models.BooleanField(blank=True, help_text='Indicates if no vital signs were recorded', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='schelud_transfer',
            field=models.BooleanField(blank=True, help_text='Indicates if a scheduled transfer was planned', null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='ambulance_cleanliness',
            field=models.CharField(blank=True, help_text='Cleanliness of the ambulance', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='ambulance_request_ease',
            field=models.CharField(blank=True, help_text='Ease of requesting the ambulance service', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='clear_info_provided',
            field=models.CharField(blank=True, help_text='Clarity of information provided about the service', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments or suggestions from the respondent', null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='driving_quality',
            field=models.CharField(blank=True, help_text='Quality of driving during the transport', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='overall_satisfaction',
            field=models.CharField(blank=True, help_text='Overall satisfaction with the ambulance service', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='phone_support_quality',
            field=models.CharField(blank=True, help_text='Quality of phone support received', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='respondent_can_sign',
            field=models.BooleanField(blank=True, help_text='Indicates if the respondent is able to sign the survey', null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='respondent_email',
            field=models.EmailField(blank=True, help_text='Email address of the respondent', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='respondent_id_number',
            field=models.CharField(blank=True, help_text='ID number of the respondent', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='respondent_name',
            field=models.CharField(blank=True, help_text='Name of the respondent', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='respondent_phone',
            field=models.CharField(blank=True, help_text='Phone number of the respondent', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='respondent_signature',
            field=models.TextField(blank=True, help_text='Digital signature of the respondent in base64 format', null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='return_trip_timeliness',
            field=models.CharField(blank=True, help_text='Timeliness of the return trip', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='safety_and_reassurance',
            field=models.CharField(blank=True, help_text='Feeling of safety and reassurance provided by the staff', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='service_punctuality',
            field=models.CharField(blank=True, help_text='Punctuality of the ambulance service', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='staff_appearance',
            field=models.CharField(blank=True, help_text='Professional appearance of the ambulance staff', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='staff_empathy',
            field=models.CharField(blank=True, help_text='Empathy shown by the ambulance staff', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsurvey',
            name='would_recommend',
            field=models.CharField(blank=True, help_text='Likelihood of recommending the service to others', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='liter_minute',
            field=models.FloatField(blank=True, help_text='Oxygen flow rate in liters per minute', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='monitors_vital_signs',
            field=models.BooleanField(blank=True, help_text='Indicates if vital signs were monitored', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nasal_cannula',
            field=models.BooleanField(blank=True, help_text='Indicates if a nasal cannula was used', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='non_rebreather_mask',
            field=models.BooleanField(blank=True, help_text='Indicates if a non-rebreather mask was used', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='oxygen',
            field=models.BooleanField(blank=True, help_text='Indicates if oxygen was administered', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='simple_face_mask',
            field=models.BooleanField(blank=True, help_text='Indicates if a simple face mask was used', null=True),
        ),
    ]
