# Generated by Django 6.0.1 on 2026-01-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0005_remove_companion_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretransferreport',
            old_name='attending_staff_tittle',
            new_name='attending_staff_title',
        ),
        migrations.RemoveField(
            model_name='companion',
            name='identification_type',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='substances',
        ),
        migrations.AddField(
            model_name='patienttransportreport',
            name='completion_percentage',
            field=models.IntegerField(default=0, help_text='Percentage of required fields completed (0-100)'),
        ),
        migrations.AddField(
            model_name='patienttransportreport',
            name='has_care_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patienttransportreport',
            name='has_informed_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patienttransportreport',
            name='has_patient_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patienttransportreport',
            name='has_satisfaction_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='home_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_provider_patient', to='patient_transport_report.insuranceprovider'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='issue_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='membership_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_history_patient', to='patient_transport_report.patienthistory'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='alcohol_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='has_allergies',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='has_medicines',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='has_pathology',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='has_surgies',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='substance_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienthistory',
            name='tobacco_use',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
