# Generated by Django 6.0.1 on 2026-01-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0006_rename_attending_staff_tittle_caretransferreport_attending_staff_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='patient_age',
        ),
    ]
