# Generated by Django 6.0.1 on 2026-01-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0007_rename_age_patient_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincondition',
            name='order',
            field=models.IntegerField(default=0, help_text='Order for displaying skin conditions'),
        ),
    ]
