# Generated by Django 6.0.1 on 2026-01-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0008_skincondition_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hemodynamicstatus',
            options={'ordering': ['order'], 'verbose_name': 'Hemodynamic Status', 'verbose_name_plural': 'Hemodynamic Statuses'},
        ),
        migrations.AlterModelOptions(
            name='skincondition',
            options={'ordering': ['order'], 'verbose_name': 'Skin Condition', 'verbose_name_plural': 'Skin Conditions'},
        ),
        migrations.AddField(
            model_name='hemodynamicstatus',
            name='order',
            field=models.IntegerField(default=0, help_text='Order for displaying hemodynamic statuses'),
        ),
        migrations.AlterField(
            model_name='skincondition',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this option is available for selection'),
        ),
    ]
