# Generated by Django 6.0.1 on 2026-01-28 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0009_alter_hemodynamicstatus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patienthistory',
            old_name='has_surgies',
            new_name='has_surgeries',
        ),
    ]
