# Generated by Django 6.0.1 on 2026-01-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0010_rename_has_surgies_patienthistory_has_surgeries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretransferreport',
            old_name='final_physical_examination',
            new_name='final_physical_exam',
        ),
        migrations.RenameField(
            model_name='caretransferreport',
            old_name='initial_physicial_examination',
            new_name='initial_physicial_exam',
        ),
    ]
