# Generated by Django 6.0.1 on 2026-01-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0011_rename_final_physical_examination_caretransferreport_final_physical_exam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretransferreport',
            old_name='initial_physicial_exam',
            new_name='initial_physical_exam',
        ),
    ]
