# Generated by Django 6.0.1 on 2026-01-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0012_rename_initial_physicial_exam_caretransferreport_initial_physical_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requiredprocedures',
            old_name='immovilization',
            new_name='immobilization',
        ),
        migrations.RenameField(
            model_name='requiredprocedures',
            old_name='other_procedures_details',
            new_name='other_procedure_details',
        ),
    ]
