# Generated by Django 6.0.1 on 2026-01-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0013_rename_immovilization_requiredprocedures_immobilization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requiredprocedures',
            old_name='streatcher_transfer',
            new_name='stretcher_transfer',
        ),
    ]
