# Generated by Django 6.0.1 on 2026-01-28 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0014_rename_streatcher_transfer_requiredprocedures_stretcher_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who soft deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag for GDPR compliance'),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
