# Generated by Django 6.0.1 on 2026-01-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0015_satisfactionsurvey_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='liter_minute',
            new_name='liters_minute',
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='coverage_type',
            field=models.CharField(blank=True, help_text='Type of insurance coverage', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='other_coverage_type',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='provider_name',
            field=models.CharField(blank=True, help_text='Name of the insurance provider', max_length=200, null=True),
        ),
    ]
