# Generated by Django 6.0.1 on 2026-01-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0016_rename_liter_minute_treatment_liters_minute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretransferreport',
            name='reg_number',
        ),
    ]
