# Generated by Django 6.0.1 on 2026-01-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0017_remove_caretransferreport_reg_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_age',
        ),
    ]
