# Generated by Django 6.0.1 on 2026-01-29 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0018_remove_patient_patient_age'),
        ('staff', '0002_remove_basestaff_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretransferreport',
            name='attending_staff_title',
        ),
        migrations.RemoveField(
            model_name='informedconsent',
            name='attending_staff',
        ),
        migrations.RemoveField(
            model_name='informedconsent',
            name='responsible',
        ),
        migrations.AddField(
            model_name='patienttransportreport',
            name='attending_staff',
            field=models.ForeignKey(blank=True, help_text='Healthcare staff attending during consent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending_staff_informed_consents', to='staff.healthcare'),
        ),
    ]
