# Generated by Django 6.0.1 on 2026-01-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0019_remove_caretransferreport_attending_staff_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='identification_number',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
