# Generated by Django 6.0.1 on 2026-01-29 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0020_alter_patient_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complicationstransfer',
            name='waiting_time',
            field=models.CharField(blank=True, help_text='Waiting time duration', null=True),
        ),
        migrations.AlterField(
            model_name='patienttransportreport',
            name='patient',
            field=models.ForeignKey(help_text='Patient associated with this transport report', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_reports', to='patient_transport_report.patient'),
        ),
    ]
