# Generated by Django 6.0.1 on 2026-01-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0021_alter_complicationstransfer_waiting_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caretransferreport',
            name='attending_staff',
        ),
    ]
