# Generated by Django 6.0.1 on 2026-01-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0022_remove_caretransferreport_attending_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='identification_number',
            field=models.CharField(blank=True, db_index=True, help_text='Identification document number', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='outgoingreceivingentity',
            name='document',
            field=models.CharField(blank=True, db_index=True, help_text='Document identifier of the entity', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identification_number',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
