# Generated by Django 6.0.1 on 2026-01-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_transport_report', '0024_alter_companion_identification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfactionsurvey',
            name='satisfaction_survey_conducted',
            field=models.BooleanField(blank=True, help_text='Indicates if the satisfaction survey was conducted', null=True),
        ),
        migrations.AlterField(
            model_name='caretransferreport',
            name='ips',
            field=models.CharField(blank=True, help_text='IPS associated with the care transfer report', max_length=100, null=True),
        ),
    ]
